import React, { Fragment } from 'react';
import Link from 'next/link';
import {useRouter} from 'next/router';
import Head from 'next/head';
import Layout from '../../../../src/layout';
import Nav from '../../../../src/shared/nav/nav';
import {listaTesis} from '../../../../src/lineas/criosfera/proyectos/iat_glaciar/componentes/produccion/lista/lista.tesis';

export default function Home () {
    const router = useRouter();
    return (
        <Layout>
            <Head>
                <title>Criósfera, Clima y Seguridad Hídrica</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700;800&display=swap" rel="stylesheet" />
            </Head>
            <main>
                <Nav />
                <div className='relative'>
                    <img className='h-80 lg:h-96 w-full cover' src='/fondos/laguna_pequeña.jpg'/>
                    <Link href='/criosfera/iat_glaciar'>
                        <a>
                            <code><h1 className='flex items-center justify-center lg:hidden absolute bottom-0 left-0 bg-white h-12 w-12 font-bold text-color text-white text-xl'>{`<`}</h1></code>
                        </a>
                    </Link>
                </div>
                <div className='flex justify-center lg:justify-center pb-16 px-4 lg:px-16 mt-10'>
                    {
                        listaTesis.map((item)=>{
                            if(item.ruta === router.query.pid){
                                return <Fragment>
                                    <div className='flex gap-5 flex-1 max-w-6xl'>
                                        <div>
                                            <Link href='/criosfera/iat_glaciar'>
                                                <a className='h-7'>
                                                    <div className='flex items-center lg:flex hidden lg:flex'>
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" className="bi bi-arrow-left-short" viewBox="0 0 16 16">
                                                            <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
                                                        </svg>
                                                        <h1 className='text-sm'>VOLVER</h1>
                                                    </div>
                                                </a>
                                            </Link>
                                            <div className='flex flex-col flex-1 w-full md:max-w-2xl lg:max-w-3xl mt-5'>
                                                <h1 className='font-bold text-xl text-justify'>{item.titulo}</h1>
                                                <h1 className='text-sm mt-1'>Abril del 2023</h1>
                                                <h1 className='mt-5 font-bold'>Planteamiento del problema</h1>
                                                <h1 className={`mt-2 text-justify ${item.descrip1 === null?'hidden':'block'} `}>{item.descrip1}</h1>
                                                <h1 className={`mt-2 text-justify ${item.descrip2 === null?'hidden':'block'} `}>{item.descrip2}</h1>
                                                <h1 className={`mt-2 text-justify ${item.descrip3 === null?'hidden':'block'} `}>{item.descrip3}</h1>
                                                <h1 className={`mt-2 text-justify ${item.descrip4 === null?'hidden':'block'} `}>{item.descrip4}</h1>
                                                <h1 className={`mt-2 text-justify ${item.descrip5 === null?'hidden':'block'} `}>{item.descrip5}</h1>
                                                <h1 className={`mt-2 text-justify ${item.descrip6 === null?'hidden':'block'} `}>{item.descrip6}</h1>
                                            </div>
                                        </div>
                                        <div className='flex-1'>
                                            <div className='background-color p-5'>
                                                <h1 className='font-bold'>Autores</h1>
                                                <h1 className='mt-3'><span className='font-bold'>Tesista: </span>{item.tesista}</h1>
                                                <h1 className=''><span className='font-bold'>Asesor: </span>{item.asesor}</h1>
                                                <h1 className=''><span className='font-bold'>Co-Asesor </span>{item.co_asesor}</h1>
                                                <h1 className=''><span className='font-bold'>Asistente de investigación: </span>{item.asist_inves}</h1>
                                            </div>
                                        </div>
                                    </div>
                                </Fragment>
                            }
                        })
                    }
                </div>
            </main>
        </Layout>
    )
}