export const listaTeam= [
    {
        id:1,
        ruta:'edi-yocsari-septimo-villacaqui',
        foto:'/section/Clima.jpg',
        name:'Edi Yocsari Séptimo Villacaqui',
        cargo:'Apoyo administrativo',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'EQUIPO INAIGEM',
        profesion: 'Licenciada en Contabilidad',
        especialidad: 'Diplomado en Gestión Administración y Gestión Pública.',
        descripcion:'Contador público, con experiencia profesional en el sector privado y público, en los temas tributarios (declaraciones de PDT621), elaboración de balance general de empresas del sector privado , elaboración de planilla, manejo de programas contables (Siscontsmart2021) y asistente administrativo.',
        correo:'mailto:yocsari95@gmail.com',
        email:'Enviar correo',
        linkedin:'https://pe.linkedin.com/in/edi-yocsari-septimo-villacaqui-8bb9b4149',
        ctvitae:null,
        orcid:null,
        pucp:null,
        harvard:null,
        researchgate:null
    },
    {
        id:2,
        ruta:'yadira-andrea-curo-rosales',
        foto:'/section/Clima.jpg',
        name:'Yadira Andrea Curo Rosales',
        cargo:'Consultora',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'EQUIPO INAIGEM',
        profesion:'Ingeniera Ambiental',
        especialidad:'Maestría en "Técnicas de Gestión del Medio Ambiente y del Territorio" / (2020) Universitat de València y Diplomado en "Gestión Ambiental" (2016) / Universidad Nacional de Ingeniería.',
        descripcion:'Ingeniera Ambiental de la Universidad Nacional Santiago Antúnez de Mayolo (V superior) - Ancash, con experiencia en trabajos con comunidades en los Andes peruanos, sistematización, organización y procesamiento de datos glaciológicos y geomáticos aplicados a recursos hídricos, he participado en proyectos de cooperación internacional,  durante mi carrera profesional he participado de las publicaciones de documentos técnicos y manuales metodológicos para el estudio de los glaciares y los ecosistemas de montaña.',
        correo:'mailto:yadira.acr@gmail.com',
        email:'Enviar correo',
        linkedin:null,
        ctvitae:"https://ctivitae.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=143570",
        orcid:"https://orcid.org/0000-0001-8229-2753",
        pucp:null,
        harvard:null,
        researchgate:"https://www.researchgate.net/profile/Yadira-Curo"
    },
    {
        id:3,
        ruta:'guadalupe-angélica-heredia-gutierrez',
        foto:'/section/Clima.jpg',
        name:'Guadalupe Angélica Heredia Gutierrez',
        cargo:'Voluntaria',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'EQUIPO INAIGEM',
        profesion:'Bachiller en Ingeniería Ambiental',
        especialidad:null,
        descripcion:'Bachiller en Ingeniería Ambiental, con experiencia en monitoreo de calidad ambiental de agua, aire, suelo y ruido ambiental. Además de haber brindado capacitaciones a personal de unidades menores de hidrocarburos en temas ambientales (Residuos sólidos, cambio climático y seguridad). Con interés en la temática socioambiental en las comunidadaes con influencia glaciar. Tesis en desarrollo en la temática de seguridad hídrica.',
        correo:'mailto:guadalupeherediagutierrez@gmail.com',
        email:'Enviar correo',
        linkedin:"https://www.linkedin.com/in/guadalupe-heredia-676259180/",
        ctvitae:null,
        orcid:null,
        pucp:null,
        harvard:null,
        researchgate:null
    },
    {
        id:4,
        ruta:'miluska-pamela-alejo-mosquera',
        foto:'/section/Clima.jpg',
        name:'Miluska Pamela Alejo Mosquera',
        cargo:'Consultora',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'EQUIPO INAIGEM',
        profesion:'Ingeniera Ambiental',
        especialidad:null,
        descripcion:'Ingeniera Ambiental de la UNASAM (V superior) - Ancash. Experiencia en estudios de ecología. Participación en proyectos de investigación enfocados al estudio de ecosistemas de montaña, así como en biodiversidad en bosques xéricos y andinos. Conocimiento en tecnologías GIS, manejo de herramientas de estadística ecológica y estimación de la biodiversidad.',
        correo:'mailto:mp.alejo.mosquera@gmail.com',
        email:'Enviar correo',
        linkedin:"https://www.linkedin.com/in/miluska-pamela-alejo-mosquera-91a2bb223",
        ctvitae:"https://dina.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=274222",
        orcid:"https://orcid.org/0000-0002-6510-7875 ",
        pucp:null,
        harvard:null,
        researchgate:null
    },
    {
        id:5,
        ruta:'eli-jadiel-chauca-figueroa',
        foto:'/section/Clima.jpg',
        name:'Elí Jadiel Chauca Figueroa',
        cargo:'Tesista de pregrado voluntario',
        ubicacion: 'Áncash, Perú',
        equipo:'EQUIPO INAIGEM',
        universidad:'UNASAM',
        profesion:'Ingeniero Ambiental',
        especialidad:null,
        descripcion:'Ingeniero Ambiental de la Universidad Nacional Santiago Antúnez de Mayolo (UNASAM) - Ancash. Tengo experiencia en proyectos de investigación relacionados a entornos glaciares con técnicas de fotogrametría, así como teledetección, herramientas GIS y monitoreos ambientales.',
        correo:'mailto:elijadiel05@gmail.com',
        email:'Enviar correo',
        linkedin:null,
        ctvitae:null,
        orcid:'https://orcid.org/0000-0003-1739-8492',
        pucp:null,
        harvard:null,
        researchgate:null,
    },
    {
        id:6,
        ruta:'victor-smith-medina-cotrina',
        foto:'/section/Clima.jpg',
        name:'Víctor Smith Medina Cotrina',
        cargo:'Consultor',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'EQUIPO INAIGEM',
        profesion:'Bachiller en Ingeniería Ambiental',
        especialidad:null,
        descripcion:'Bachiller en ingeniería ambiental de la Universidad Nacional Santiago Antúnez de Mayolo (UNASAM), un apasionado por el aprendizaje automático y la ciencia de datos para la comprensión, monitoreo y predección del cambio ambiental. Particularmente interesado en la programación en redes neuronales artificiales, clasificación de imágenes y detección de objetos aplicados a la investigación en glaciares y a la conservación de Áreas Naturales Protegidas (ANPs).',
        correo:'mailto:smith_12_47@hotmail.com',
        email:'Enviar correo',
        linkedin:'https://www.linkedin.com/in/v%C3%ADctor-smith-medina-cotrina-28155159/',
        ctvitae:null,
        orcid:null,
        pucp:null,
        harvard:null,
        researchgate:null
    },
]