import Head from 'next/head'
import Layout from '../src/layout';
import dynamic from 'next/dynamic';

const MapViewer = dynamic(()=>import('../src/visor/map.view'), {ssr: false});

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Criósfera, Clima y Seguridad Hídrica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Material+Icons+Outlined" />

      </Head>
      <div id="map">
        <MapViewer />
      </div>
    </Layout>
  )
}
